# Makefile for C Pointer Activity
# Kyle McCoy, RIT, 02/19/19

default: test_pointers

test_pointers:	main.c read_data.c 
	gcc -g -Wall -o test_pointers main.c read_data.c

clean:
	rm -f test_pointers
